### ISSUE TITLE
Testuite failures on windows 7 python 3.4.3 64bit

### ISSUE THREAD

**Issue by itziakos** [itziakos/zipfile2#22]
``` python
........C:\Users\itziakos\Projects\zipfile2\zipfile2\_zipfile.py:156: UserWarning: Duplicate name: 'file.py'
  compress_type)
.....EEEE......
======================================================================
ERROR: test_softlink (zipfile2.tests.test__zipfile.TestZipFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\tests\test__zipfile.py", line 145, in test_softlink
    zp.extractall(self.tempdir)
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\_zipfile.py", line 97, in extractall
    self.extract(zipinfo, path, pwd, preserve_permissions)
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\_zipfile.py", line 72, in extract
    return self._extract_member(member, path, pwd, preserve_permissions)
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\_zipfile.py", line 161, in _extract_member
    targetpath, pwd, preserve_permissions)
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\_zipfile.py", line 216, in _extract_member_to
    targetpath = self._extract_symlink(member, targetpath, pwd)
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\_zipfile.py", line 167, in _extract_symlink
    os.symlink(source, link_name)
OSError: symbolic link privilege not held

======================================================================
ERROR: test_softlink_with_broken_entry (zipfile2.tests.test__zipfile.TestZipFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\tests\test__zipfile.py", line 180, in test_softlink_with_br
oken_entry
    create_broken_symlink(existing_link)
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\tests\test__zipfile.py", line 78, in create_broken_symlink
    os.symlink(os.path.join(d, "nono_le_petit_robot"), link)
OSError: symbolic link privilege not held

======================================================================
ERROR: test_write_symlink_directory (zipfile2.tests.test__zipfile.TestZipFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\tests\test__zipfile.py", line 297, in test_write_symlink_di
rectory
    os.symlink(os.path.dirname(real_file), symlink)
OSError: symbolic link privilege not held

======================================================================
ERROR: test_write_symlink_file (zipfile2.tests.test__zipfile.TestZipFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\itziakos\Projects\zipfile2\zipfile2\tests\test__zipfile.py", line 261, in test_write_symlink_fi
le
    os.symlink(real_file, symlink)
OSError: symbolic link privilege not held

----------------------------------------------------------------------
Ran 23 tests in 1.449s

FAILED (errors=4)
```

**Comment by cournape** [comment]
That may be relevant: http://stackoverflow.com/questions/2094663/determine-if-windows-process-has-privilege-to-create-symbolic-link
